



pool:
  vmImage: 'windows-latest'
stages:
- stage: ApiAutomationTests
  displayName: "Api Automation Test"
  jobs:
  - job: runTests
    displayName: "run automated tests"
    steps:
      - 
     - script: "npm install -g newman"
      displayName: "Install Newman"

    - script: "newman run ApiLearning.json -e ApiAutomationEnvironment.json --reporters cli,junit --reporter-junit-export Results/junitReport.xml "
      displayName: "Run Postman Collection"

    - task: publishTestResults@2
      displayName: "Publish Test Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: "**/*.xml"
        searchFolder: "Results"
        testRunTitle: "Newman Regression Tests"

